name: Build CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: npm run build

  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}

    steps:

    - name: Config SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/remote.key
        chmod 600 ~/.ssh/remote.key
        cat >>~/.ssh/config <<END
        Host remote
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/remote.key
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
        END
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}

    - name: Copy build 
      run: rsync -r build remote:/home/$SSH_USER/ledger-graphql

    - name: Copy package.json 
      run: rsync package.json remote:/home/$SSH_USER/ledger-graphql

    - name: Start web server 
      run: ssh remote 'start.sh'
    
