name: Build CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - run: npm ci
    - run: npm run build

  
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Stop web server 
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: ${{ secrets.SERVER_HOST }}
        privateKey: ${{ secrets.PRIVATE_KEY }}
        command: stop.sh 
    - name: Copy build to server 
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.SERVER_HOST }}
        local: build
        remote: ledger-graphql
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Copy package.json to server 
      uses: garygrossgarten/github-action-scp@release
      with:
        host: ${{ secrets.SERVER_HOST }}
        local: package.json
        remote: ledger-graphql
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Install dependencies and start web server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: ${{ secrets.SERVER_HOST }}
        privateKey: ${{ secrets.PRIVATE_KEY }}
        command: npm ci && start.sh 
