name: Trigger CD/CI

on:
  push:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Config SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/remote.key
        chmod 600 ~/.ssh/remote.key
        cat >>~/.ssh/config <<END
        Host remote
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/remote.key
          StrictHostKeyChecking no
          UserKnownHostsFile /dev/null
        END
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}

    - name: Trigger build process 
      run: ssh remote 'ledger-graphql'
    
